import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Code2, Zap, Layout, ArrowRight } from 'lucide-react';

const LandingPage = () => {
  const navigate = useNavigate();

  return (
    <div className="container animate-fade-in" style={{ textAlign: 'center', paddingTop: '10vh' }}>
      
      <div style={{ marginBottom: '3rem' }}>
        <h1 style={{ fontSize: '4rem', marginBottom: '1rem' }}>
          Intelligent <span className="gradient-text">Code Review</span> Chatbot
        </h1>
        <p style={{ fontSize: '1.25rem', color: 'var(--text-muted)', maxWidth: '600px', margin: '0 auto' }}>
          Upload your Java or Python code and instantly get line-by-line explanations, time complexity analysis, and performance-optimized code generated by cutting-edge Hugging Face AI.
        </p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'center', gap: '1rem', marginBottom: '4rem' }}>
        <button className="btn-primary" onClick={() => navigate('/auth')}>
          Get Started <ArrowRight size={20} />
        </button>
        <button className="btn-secondary" onClick={() => navigate('/auth')}>
          View Documentation
        </button>
      </div>

      <div className="dashboard-grid" style={{ textAlign: 'left', gridTemplateColumns: 'repeat(3, 1fr)' }}>
        <div className="glass-panel">
          <Code2 size={32} color="var(--accent-color)" style={{ marginBottom: '1rem' }} />
          <h3>Deep Explanations</h3>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>Get line-by-line semantic breakdowns of complex code logic.</p>
        </div>
        <div className="glass-panel">
          <Zap size={32} color="#00d4ff" style={{ marginBottom: '1rem' }} />
          <h3>Optimization Engine</h3>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>Instantly receive the optimized version with Big-O complexity improvements.</p>
        </div>
        <div className="glass-panel">
          <Layout size={32} color="#ff42a1" style={{ marginBottom: '1rem' }} />
          <h3>Professional UX</h3>
          <p style={{ color: 'var(--text-muted)', marginTop: '0.5rem' }}>A seamless, dark-themed developer experience with beautiful visualizations.</p>
        </div>
      </div>

    </div>
  );
};

export default LandingPage;
